---
- name: Installer Apache uniquement sur Debian
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Installer Apache2 (Debian only)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: install_apache

    - name: Confirmer l’installation d’Apache
      ansible.builtin.debug:
        msg: >
          Apache a été installé sur {{ inventory_hostname }}
      when: install_apache.changed | default(false)
