---
- name: Désinstaller complètement Apache2
  hosts: localhost
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets (apt)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Désinstaller tous les paquets apache2*
      ansible.builtin.apt:
        name: "apache2*"
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Désinstaller apache2 (pour compatibilité multi-OS)
      ansible.builtin.package:
        name: apache2
        state: absent

    - name: Vérifier si apache2 est encore installé
      ansible.builtin.command: apache2 -v
      register: apache_version
      ignore_errors: yes

    - name: Afficher le résultat de la désinstallation
      ansible.builtin.debug:
        msg: |
          {% if apache_version.rc != 0 %}
            Apache2 n'est plus installé.
          {% else %}
            Apache2 est encore présent : {{ apache_version.stdout }}
          {% endif %}
