---
- name: Créer plusieurs utilisateurs par boucle
  hosts: all
  become: true
  gather_facts: true

  vars:
    utilisateurs:
      - karim
      - sarah
      - louis

  tasks:
    - name: Créer les comptes utilisateurs
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ utilisateurs }}"
