---
- name: Déployer l'application Node.js quiz-ansible sur Rocky Linux via script
  hosts: rocky
  become: true
  gather_facts: true

  vars:
    local_script: scripts/quiz-ansible.sh
    remote_script: /tmp/quiz-ansible.sh

  tasks:
    - name: Copier le script de déploiement
      ansible.builtin.copy:
        src: "{{ local_script }}"
        dest: "{{ remote_script }}"
        mode: '0755'

    - name: Exécuter le script quiz-ansible.sh
      ansible.builtin.shell: bash "{{ remote_script }}"
      args:
        creates: /opt/quiz-ansible
      register: deploy_run
      changed_when: deploy_run.rc == 0

    - name: Attendre que l'application écoute sur 127.0.0.1:3000
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 3000
        delay: 5
        timeout: 120
      register: wait_app
      ignore_errors: yes

    - name: Afficher les 20 dernières lignes du log en cas d’échec
      ansible.builtin.shell: tail -n 20 /tmp/quiz-ansible.log
      register: last_logs
      when: wait_app is failed
      changed_when: false

    - name: Debug du log (si échec)
      ansible.builtin.debug:
        var: last_logs.stdout_lines
      when: wait_app is failed
